### ISSUE TITLE
Formatter not working sometimes

### ISSUE THREAD

**Issue by jokeruarwentto** [howaajin/graphformatter#11]
The formatter is only working on the tab that was opened first, if you are leaving your blueprint on **Construction Script** and reopening it, the formatter will and only formatter this tab. Even if you are trying to format an function, it'll format and the opened tab.

If you are leaving your blueprint on your function tab, and reopening it, the formatter will work on this tab, if you try to format the **Construction Script** it'll format the older tab, the function that was opened first.

I don't know if the explaination will be correct but, here a gif explaining the problem:

![GIF 30-12-2022 23-25-26](https://user-images.githubusercontent.com/7479947/210115587-af189f56-088f-4ee4-83af-eb004b4f5cdc.gif)

Windows 11 Pro x64
Unreal Engine 5.1 (latest at this day)
GraphFormatter v2.3.0 [Latest](https://github.com/howaajin/graphformatter/releases/latest)

**Comment by howaajin** [comment]
I have noticed this problem. This is because when the node is not displayed on the screen, the position of the node returned by calling Unreal's function is incorrect. I used to do some hacking to get the correct position. Due to recent changes, this somewhat hacky method has been removed. I'll try to find other ways to fix it.

**Comment by howaajin** [comment]
Another point is that when the zoom level is different, the size of the formatted node will be different, which will also cause the result to be confused after zooming in. For these problems, I will try to use the engine‘s native method first, and if it doesn’t work, I will go back to the old method
