### ISSUE TITLE
Not works on Unreal 5.4

### ISSUE THREAD

**Issue by sevelee** [howaajin/graphformatter#19]
Try to build it with unreal 5.4.2  and get a lot of missing define errors.

**Comment by howaajin** [comment]
I tested the most recent version 5.4.4 of version 5.4, and I was able to successfully build it using the command "python Build.py --v 5.4".

**Comment by sevelee** [comment]
@howaajin Sorry for didn't update the issue. The problem is our team changed the "bAdaptiveUnityDisablesOptimizations" of the project. If enable Adaptive Unity Optimization, I could build the plugin successfully.
