### ISSUE TITLE
How does graph layout work?

### ISSUE THREAD

**Issue by fire** [howaajin/graphformatter#2]
Hi! 

I was wondering how math-wise you rearranged your graphs.

https://github.com/OpenKieler/elkjs Looks complicated but it is one of the better ones.

The goal is to write something similar for Godot Game Engine.

**Comment by howaajin** [comment]
It is based on the ideas  of [Layered graph drawing](https://en.wikipedia.org/wiki/Layered_graph_drawing).
These papers may help:
 [Fast and Simple Horizontal Coordinate Assignment](https://link.springer.com/chapter/10.1007/3-540-45848-4_3)
[Size- and Port-Aware Horizontal Node Coordinate Assignment](https://link.springer.com/chapter/10.1007/978-3-319-27261-0_12).
