### ISSUE TITLE
Not an issue just a quesiton or request.

### ISSUE THREAD

**Issue by oivio** [howaajin/graphformatter#3]
First, thank you for an amazing Plugin! Because of some issues with UE44.23 I'm going back to 4.19 so here is my question. Is there a chance to get that plugin working on 4.19?

**Comment by howaajin** [comment]
You can download this repository and put it under the Plugins folder of your project. If it works, there's no need to change the code. If not, please let me know. I have to switch to 4.19 and compile it for testing. Currently I can not do that.

**Comment by howaajin** [comment]
I comfirm that this plugin don't work with UE4.21 below.
Due to many API changed from 4.19 to 4.21, I have no plan to support below 4.21.
