### ISSUE TITLE
crashing when use alt+f key on unreal 4.26

### ISSUE THREAD

**Issue by znoose** [howaajin/graphformatter#4]
just crashing when I use it on 4.26 version... no explanation... I'm not programming so I eaven't solution

**Comment by howaajin** [comment]
Sorry for the late reply 😔, can you tell me which platform you use? Mac or Windows?

**Comment by howaajin** [comment]
See this [commit](https://github.com/howaajin/graphformatter/commit/4845054bf15629354cb6d93e74895985a0fe76a1).
