### ISSUE TITLE
Crashing the Auto Format graph mode (Alt+f) at Debug mode

### ISSUE THREAD

**Issue by hooni7440** [howaajin/graphformatter#6]
Hi there is error on Auto Format Graph mode at Debug Editor mode.
I think it cannot run on GetGraphEditor functions at FormatterHacker.cpp but I don't know which one...
And also I rolled back myself at 'SGraphEditor* GetGraphEditor(const FBehaviorTreeEditor* Editor)' because FAccessAIGraphEditor and FPrivateAccessor made error C2065, C2923 and C2955.

Here's the screenshot when Auto Format Graph mode error occurred.
![image](https://user-images.githubusercontent.com/20672661/107351199-ac09c380-6b0d-11eb-8d35-c328994ddac1.png)

**Comment by hooni7440** [comment]
It doesn't problem at development editor mode by the way

**Comment by howaajin** [comment]
See Technical Details section here https://www.unrealengine.com/marketplace/en-US/product/graph-formatter
I use Template Specialization to access the private fields of UE4 Object. This is not working on debug build, seems  the MSVC compiler don't provide right address of the private members. If you want to run it in debug mode you have to find the right address.

**Comment by hooni7440** [comment]
Ahh I see. Thanks for notice about that and I really satisfy this plugin btw!
