### ISSUE TITLE
Question: Would you open to a pull request for extending integration with custom editors ?

### ISSUE THREAD

**Issue by mklabs** [howaajin/graphformatter#7]
Hi!

I recently worked on a custom graph editor and been experimenting with format / auto arrange feature for the nodes available in the graph.

Then, I decided to try out Graph Formatter, was completely blown away by it, and decided to try it out with my own plugin. And the result were just great!

Integration was surprisingly easy: https://github.com/mklabs/graphformatter/compare/master...combograph-integration

My question is: If I find a better way to expand the ability in Graph Formatter to support custom Editors (that are not SoundCue, Blueprint, AIGraph editors etc.), without expressing a hard dependency on other plugins, would you be open to a Pull Request ?

I'm thinking about a way to hook into the Formatter Hacker and register delegates for custom editors, possibly through configuration via .ini files. I'm not sure yet.

---

And thanks for this awesome piece of work!

**Comment by howaajin** [comment]
Hi,

Any changes to make things better are welcome.

Currently, the graph types this plugin supported are hard coded, especially for behavior tree graph, the nodes in layers are sorted according to a special key.  This special things must take into account. Hope this information helps.

**Comment by mklabs** [comment]
Hi @howaajin 

Thanks a lot for your response. I haven't had the time to look further into this, but if I manage to find a solution, I'll work on a Pull Request.

The main thing I'd like to avoid is adding an hard dependency to other plugins / modules to graphformatter. I'll let you know if I find anything ;)
